language: php

php:
  - 5.4

before_install:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start

before_script:
   - npm install
   - node_modules/karma/bin/karma start my.conf.js --single-run

script:
   - phpunit
